defaults:
  - prompts: prompts_01
  - data: data_01
  - models: models_01
  - pre_proc: pre_proc_01
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

vector_db:
  chunk_size: 512
  chunk_overlap: 128
  embedding_model: sentence-transformers/all-MiniLM-L6-v2
  collection_name: sec_10k_19_Jan
  qdrant_path: ${hydra.runtime.cwd}/qdrant_db

hydra:
  verbose: false
